name: windows-msvc

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: checkout premake5
      uses: actions/checkout@v2
      with:
        repository: premake/premake-core
        path: premake-build

    - name: Build premake5
      run: |
        $vcvarall_path = vswhere -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarall_path"" x86_amd64 && cd premake-build && nmake -f Bootstrap.mak MSDEV=vs2019 windows-msbuild PLATFORM=Win32 CONFIG=release && cp bin/release/premake5.exe ../tests"

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: cache-windows64-Qt6.3.0

    - name: Installing Qt - 6.3.0 win64_msvc2019_64
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.3.0'
        arch: win64_msvc2019_64
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: test premake-qt
      run: |
        echo $PATH
        cd tests
        PATH=$PATH:`pwd` ./test_projects.sh premake5 vs2019 premake5.lua --qt-root=$Qt6_DIR
        cd ..
      shell: bash
